---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prow
  name: sinker
  labels:
    app: sinker
spec:
  selector:
    matchLabels:
      app: sinker
  replicas: 1
  template:
    metadata:
      labels:
        app: sinker
    spec:
      serviceAccountName: "sinker"
      containers:
      - name: sinker
        image: gcr.io/k8s-prow/sinker:v20220331-c4e1c201d5
        args:
        - --config-path=/etc/config/config.yaml
        - --job-config-path=/etc/job-config
        - --dry-run=false
        env:
        - name: KUBECONFIG
          value: "/etc/kubeconfig-default/config:/etc/kubeconfig-prow-service-trusted/config:/etc/kubeconfig-prow-gke-build/config:/etc/kubeconfig-tkg-es-prow-build/kubeconfig-es"
        ports:
        - name: metrics
          containerPort: 9090
        volumeMounts:
        - mountPath: /etc/kubeconfig-default
          name: kubeconfig-default
          readOnly: true
        - mountPath: /etc/kubeconfig-prow-service-trusted
          name: kubeconfig-prow-service-trusted
          readOnly: true
        - mountPath: /etc/kubeconfig-prow-gke-build
          name: kubeconfig-prow-gke-build
          readOnly: true
        - mountPath: /etc/kubeconfig-tkg-es-prow-build
          name: kubeconfig-tkg-es-prow-build
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: job-config
          mountPath: /etc/job-config
          readOnly: true
      volumes:
      - name: kubeconfig-default
        secret:
          defaultMode: 420
          secretName: kubeconfig-default
      - name: kubeconfig-prow-service-trusted
        secret:
          defaultMode: 420
          secretName: kubeconfig-prow-service-trusted
      - name: kubeconfig-prow-gke-build
        secret:
          defaultMode: 420
          secretName: kubeconfig-prow-gke-build
      - name: kubeconfig-tkg-es-prow-build
        secret:
          defaultMode: 420
          secretName: kubeconfig-tkg-es-prow-build
      - name: config
        configMap:
          name: config
      - name: job-config
        configMap:
          name: job-config
